### ISSUE TITLE
Errors when using Internet Explorer [as e2e test device]

### ISSUE THREAD

**Issue by atifansari13** [Evilweed/protractor-beautiful-reporter#105]
Here are several errors i am getting with IE.
**1. Unable to determine type from: E. Last 1 characters read: E**
      at Module.m._compile (C:\Users\a\*\node_modules\ts-node\src\index.ts:400:23)
        at Module._extensions..js (module.js:663:10)
        at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\a\*\node_modules\ts-node\src\index.ts:403:12)
  Message:
    **Failed: Unable to determine type from: E. Last 1 characters read: E
    Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'**

**2.  Failed: Timed out waiting for script to complete.**
Failed: Timed out waiting for script to complete.
    **Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
    System info: host: 'ATIF-LAPTOP', ip: '10.1.6.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
    Driver info: driver.version: unknown**

3. Screenshot dir

**Error: Error: Please pass a valid base directory to store the screenshots into.**

Everything works fine with Chrome

**Comment by miller45** [comment]
@atifansari13 Try first with running the e2e test without the protractor beautiful reporter...

I had hard time making it possible: The message "driver.version: unknown showed up" on my system as long as it had problems starting the ie-driver. 
But after that reporter works fine with IE on Windows 7...

**Comment by atifansari13** [comment]
When i run e2e tests without the protractor beautiful reporter, everything works fine and i see no issues. I am using Windows 10.

**Comment by miller45** [comment]
@atifansari13 I have to check this at home because I have no access to a windows 10 machine where I am now...
bit it could be related to: 
https://github.com/seleniumhq/selenium-google-code-issue-archive/issues/6511

**Comment by miller45** [comment]
@atifansari13 how did you manage to run protractor with IE11 on windows 10? When I a start protractor (without beautiful reporter) it opens the IE browser and then does nothing until i have a timeout...and then runs through all the test with them failing....

**Comment by atifansari13** [comment]
I followed these steps to setup IE.

https://stackoverflow.com/questions/37456099/protractor-test-in-ie

**Comment by atifansari13** [comment]
Node: v8.11.4, NPM: 5.6.0, protractor: 5.3.2.

Here is my protractor.config

// Protractor configuration file, see link for more information
// https://github.com/angular/protractor/blob/master/lib/config.ts

var HtmlReporter = require('protractor-beautiful-reporter');

exports.config = {
  // SELENIUM_PROMISE_MANAGER: false,
  allScriptsTimeout: 11000,
  specs: [
      './src/test/myspec.spec.ts'

  ],

  multiCapabilities: [{
      'browserName': 'chrome'
    }, {
      'browserName': 'firefox'
    },
    {
      'browserName': 'MicrosoftEdge'
    },
    {
    'browserName': 'internet explorer'
  }],
  maxSessions: 1,
  seleniumAddress: 'http://localhost:4444/wd/hub',
  // directConnect: true,
  stackTrace: true,
  baseUrl: '/',
  framework: 'jasmine',
  jasmineNodeOpts: {
    showColors: true,
    defaultTimeoutInterval: 30000
  },
  onPrepare() {
    browser.driver.manage().window().maximize();
    browser.driver.manage().deleteAllCookies();
    browser.driver.manage().timeouts().pageLoadTimeout(20000);
    browser.driver.manage().timeouts().implicitlyWait(20000);
    require('ts-node').register({
      project: require('path').join(__dirname, './tsconfig.e2e.json')
    });
     jasmine.getEnv().addReporter(new HtmlReporter({
       baseDirectory: 'tmp/screenshots', preserveDirectory: true
     }).getJasmine2Reporter());
  }
};

**Comment by miller45** [comment]
Your config works on my system... i only left out "MicrosoftEdge" and changed the baseUrl: '/' to a full qualified url like   'http://localhost:4200' because IE did like it to open with "/".
You should have a look at link i provided...and search for the registry settings with FEATURE_BFCACHE....this is the only thing i did...besides start the webdriver-manager as **Administrator**

**Comment by atifansari13** [comment]
I updated the baseurl to 'http://localhost:4200', added the registry entry but still seeing the error.

More details.
I have a spec file which has 2 suites (2 describe blocks). 
1. Test 1 -Launch browser and do some stuff (It works fine)
2. Test 2 - launch browser and do some other stuff (it fails here).

If i remove the first test and leave the second one, it works.

I am not doing any thing like browser.close(). This works fine with all other browsers and even on IE when i remove this part from my config.
    jasmine.getEnv().addReporter(new HtmlReporter({
      baseDirectory: 'tmp/screenshots', preserveDirectory: true
    }).getJasmine2Reporter());

**Comment by miller45** [comment]
Well than I am out of ideas....so you will have to use another reporter for internet explorer....

**Comment by atifansari13** [comment]
Have you tried using the scenario where there are 2 describe blocks in the spec file? 

I am using the following versions and still seeing the problem.

node version 8.12.0 
npm version 6.4.1. 
protractor version 5.4.0
"jasmine": "3.2.0",
"jasmine-core": "~3.2.1"

**Comment by miller45** [comment]
Yes of course... i used this reference example....
https://github.com/Evilweed/protractor-beautiful-reporter/blob/master/examples/specs/example_spec.js
and also test a suite with mutliple describes in angular cli configuration...
I spend about 5 hrs for testing...
You have too see: we do not do anything specific for the browsers: We rely on the selenium webdrivers do do that job...

**Comment by miller45** [comment]
Theres one thing i want to mention (it might not be related to this problem) 
is see that you have   `specs: ["./specs/*_spec.js"]` in your protractor.conf. Do you keep your e2e test alongside your unit tests? How do make suke that webpack is not mixing up the depedencies.
You have to careful with "that" . i usually see the pattern that either the e2e test are in special folder or the e2e tests are alongside with the components but have a pattern like *.e2e.ts

**Comment by atifansari13** [comment]
My protractor.conf file is in the e2e folder. Everything related to e2e is in the e2e folder. In the project root I have package.json which is shared.

**Comment by miller45** [comment]
Can you see if internet explorer shows exceptions in the console

**Comment by atifansari13** [comment]
I enabled enableFullPageScreenshot in by protactor.conf inside multi-capabilities.

 {
    'browserName': 'internet explorer',
    'ignoreProtectedModeSettings': true,
    'enableFullPageScreenshot': false,
    'ignoreZoomSetting': true,
    'version': 11,
    'nativeEvents': false,
    'unexpectedAlertBehaviour': 'accept',
    'ignoreProtectedModeSettings': true,
    'enablePersistentHover': true,
    'disable-popup-blocking': true
  }

**I added driver.quit to onComplete function. And this is what it gave.**

 WebDriverError: Unable to determine type from: E. Last 1 characters read: E
    Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
    System info: host: 'ATIF-LAPTOP', ip: '10.1.6.2', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_181'
    Driver info: driver.version: unknown
        at Object.checkLegacyResponse (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:546:15)
        at parseHttpResponse (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:509:13)
        at doSend.then.response (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\http.js:441:30)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
    From: Task: WebDriver.takeScreenshot()
        at thenableWebDriverProxy.schedule (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:807:17)
        at thenableWebDriverProxy.takeScreenshot (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:1085:17)
        at run (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\built\browser.js:59:33)
        at ProtractorBrowser.to.(anonymous function) [as takeScreenshot] (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\built\browser.js:67:16)
        at Jasmine2Reporter._callee8$ (C:\Users\atif.ansari\ProjectHeisenberg\AppUI\node_modules\protractor-beautiful-reporter\index.js:4976:48)
        at tryCatch (C:\Users\atif.ansari\ProjectHeisenberg\AppUI\node_modules\protractor-beautiful-reporter\index.js:5403:40)
        at Generator.invoke [as _invoke] (C:\Users\atif.ansari\ProjectHeisenberg\AppUI\node_modules\protractor-beautiful-reporter\index.js:5677:22)
        at Generator.prototype.(anonymous function) [as next] (C:\Users\atif.ansari\ProjectHeisenberg\AppUI\node_modules\protractor-beautiful-reporter\index.js:5436:21)
        at step (C:\Users\atif.ansari\ProjectHeisenberg\AppUI\node_modules\protractor-beautiful-reporter\index.js:4487:191)
        at C:\Users\atif.ansari\ProjectHeisenberg\AppUI\node_modules\protractor-beautiful-reporter\index.js:4487:361
    From: Task: Run beforeEach in control flow
        at UserContext.<anonymous> (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test:
    Error
        at Jasmine2Reporter.jasmineStarted (C:\Users\atif.ansari\ProjectHeisenberg\AppUI\node_modules\protractor-beautiful-reporter\index.js:4715:13)
        at Jasmine.execute (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\lib\jasmine.js:200:12)
        at C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\built\frameworks\jasmine.js:132:15
        at Function.promise (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:682:9)
        at C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\built\frameworks\jasmine.js:104:14
        at _fulfilled (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    From: Task: Run beforeEach in control flow
        at UserContext.<anonymous> (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    From asynchronous test:
    Error
        at Jasmine2Reporter.jasmineStarted (C:\Users\atif.ansari\ProjectHeisenberg\AppUI\node_modules\protractor-beautiful-reporter\index.js:4715:13)
        at Jasmine.execute (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\lib\jasmine.js:200:12)
        at C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\built\frameworks\jasmine.js:132:15
        at Function.promise (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:682:9)
        at C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\built\frameworks\jasmine.js:104:14
        at _fulfilled (C:\Users\atif.ansari\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)


  onComplete: function(){
    driver.quit();

  }


I am not sure what typescript equivalent of this is and where it goes.

File file = ((TakesScreenshot)driver).getScreenshotAs(OutputType.FILE);

**Comment by miller45** [comment]
Ok that is some interesting input...both the error messages on top and this stracktrace have the  `driver.version: unknown` message. So at the time the screenshot should be made the driver is not "available". I am guessing that there are some issues with asynchrounous processes. 
May be i try to simulate something later...
