### ISSUE TITLE
Report generation stops after running a certain number of test cases. 

### ISSUE THREAD

**Issue by WorkingMonk5** [Evilweed/protractor-beautiful-reporter#198]
Hi, 
I am facing issue with protractor-beautiful-reporter. When i try to run my regression suite, after a point, like after execution of about 100-120 test cases, the report generation fails with the following error. 

From asynchronous test:
Error
    at Jasmine2Reporter.jasmineStarted (C:\Users\username\Documents\Repositories\bpa-automation-ui\node_modules\protractor-beautiful-reporter\index.js:4948:13)
    at dispatch (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4366:28)
    at ReportDispatcher.jasmineStarted (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4337:11)
    at Env.execute (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:975:16)
    at Jasmine.execute (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine\lib\jasmine.js:200:12)
    at C:\Users\username\AppData\Roaming\npm\node_modules\protractor\built\frameworks\jasmine.js:132:15
    at Function.promise (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:682:9)
    at C:\Users\username\AppData\Roaming\npm\node_modules\protractor\built\frameworks\jasmine.js:104:14
    at _fulfilled (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
From: Task: Run beforeEach in control flow
    at UserContext.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at QueueRunner.execute (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4199:10)
    at Spec.queueRunnerFactory (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:909:35)
    at Spec.execute (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:526:10)
    at UserContext.fn (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:5340:37)
    at attempt (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\username\AppData\Roaming\npm\node_modules\protractor\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)

Can someone help me with this. The execution of the protractor suite works fine till the end of the test run. However, the reporter does not scale up till the end of the execution. I have about 500+ test cases in my regression suite currently. I never get a full result. 
Can someone please help me and let me know if there is something i can do to help the reporter scale up to more than 500 test case results? 

Thanks,

**Comment by nitishdastane** [comment]
Same issue appears to me as well.
One of the think that I observed that when execution stops after timeout error then above error consistently one after another.

Need some help in here
