### ISSUE TITLE
PreserveDirectory false cause sometimes test fail to start

### ISSUE THREAD

**Issue by amedvedjev** [Evilweed/protractor-beautiful-reporter#58]
look like "removeDirectory(filePath);" fails sometimes and .....
```
[05:21:00][Step 4/4] [chrome #01-27] [05:21:00] E/configParser - Error code: 105
[05:21:00][Step 4/4] [chrome #01-27] [05:21:00] E/configParser - Error message: failed loading configuration file ..........
[05:21:00][Step 4/4] [chrome #01-27] [05:21:00] E/configParser - Error: ENOENT: no such file or directory, unlink '.........\reports\test\assets\angular.min.js'
[05:21:00][Step 4/4] [chrome #01-27]     at Object.fs.unlinkSync (fs.js:1061:18)
[05:21:00][Step 4/4] [chrome #01-27]     at removeDirectory (D:\tc\ba0\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:5294:20)
[05:21:00][Step 4/4] [chrome #01-27]     at Object.removeDirectory (D:\tc\ba0\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:5296:17)
[05:21:00][Step 4/4] [chrome #01-27]     at new ScreenshotReporter (D:\tc\ba0\work\a5d9398c7ec5eb82\node_modules\protractor-beautiful-reporter\index.js:4665:14)
```

**Comment by Evilweed** [comment]
@amedvedjev can You provide Your protractor.conf.js file and Your reporter settings?

**Comment by amedvedjev** [comment]
@Evilweed figured out issue. We are running tests with many protractor instances. PreserveDirectory = false cause 2 problems:
 - delete completed tests results
 - lock files while updating tests and cause fail on delete

thus "PreserveDirectory " can not be used with multiple instances runs. If it is NOT issue pls close.

**Comment by Evilweed** [comment]
True - if You are using sharding then preserve directory should be set to True. Closing as per comment.
