### ISSUE TITLE
Invalid session ID is not registered in report

### ISSUE THREAD

**Issue by HermansJarno** [Evilweed/protractor-beautiful-reporter#99]
Hi,

My beautiful-reporter isn't showing all failed tests. I have a suite with +/- 100 tests and only 34 are shown in the report. The remaining 66 tests are failing due to 'invalid session id' and are not picked up by the report.

Is there a way to show them in the report? 

Thanks in advance.

A stacktrace as example:

`exception: Failed: invalid session id   (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
WebDriverError: invalid session id
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(34 more lines...)exception: Failed: invalid session id   (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
WebDriverError: invalid session id
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(56 more lines...)exception: Failed: invalid session id   (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
WebDriverError: invalid session id
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(34 more lines...)exception: Failed: invalid session id   (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
WebDriverError: invalid session id
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-693.11.6.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/home/webuser/git/blue-e2e/node_modules/protractor/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
(474 more lines...)`

**Comment by HermansJarno** [comment]
Thanks for the fast reply!

Indeed, there should be no invalid session in the first place. It's just a bit inconvenient that bamboo shows the full result and the reporter not. SpecReporter has no issue with logging it in console so...

The issue you shared could indeed be related to my problem, since it's about multiple tests running at same time. Some of my protractor tests start java selenium tests, to test a link between two applications. Suddenly one of these selenium tests is failing on execution, causing all following tests to fail with 'invalid session id'.

**Comment by miller45** [comment]
@HermansJarno you try installing this version directly from my repo `npm install https://github.com/miller45/protractor-beautiful-reporter.git`.
In this version i catch every exception accessing the session.id.  
I don´t how if it works because it is hard to"simulate" a half crashed selenium...

**Comment by miller45** [comment]
@HermansJarno additionally you can combine pbr with additional reporters:
https://github.com/Evilweed/protractor-beautiful-reporter/wiki/Add-additional-reporters-(JUnitXmlReporter,-SpecReporter)
So you have at least the test result and can trace down why a single test disturbs the selenium ecosystem.

**Comment by miller45** [comment]
@HermansJarno Did not you have any improvements with those tips? Please give feedback.

**Comment by HermansJarno** [comment]
@miller45 Sorry that i didn't respond sooner, the invalid session id is at the moment (magically) fixed on the bamboo builds at my project. So, I can't test if your changes did the trick. I hope that the invalid session id pops up again so I can test your changes. It's indeed difficult to simulate a half crashed selenium.

We are already using multiple reports, like you pointed out to do.

**Comment by miller45** [comment]
closed until further input....

**Comment by HermansJarno** [comment]
@miller45 Trying out now at bamboo, invalid session id's were popping up again, will report back.

**Comment by miller45** [comment]
Ok...one note for anyone reading this: SpecReporter or other Reporters with no screenshots haves no problem with Invalid Session Ids because it the do not access the webdriver during testexeution. The only report what jasmine framework gives them. 
But the protractor-beautiful-reporter has to access the webdriver directly in order to make screenshots, So if the webdriver is derailed by some other testing (frameworks) it influences all reporters which rely on fully functional webdriver.

**Comment by miller45** [comment]
Closing because of no further feedback
